CREATE TABLE EDUMAN.JAVALIB_BOOKS
(
		ID NUMBER PRIMARY KEY,
		BOOK_NAME  VARCHAR2(100),
		AUTHOR VARCHAR2(100),
		CREATE_DATE DATE
);
-- TABLE COMMENT
COMMENT ON TABLE EDUMAN.JAVALIB_BOOKS IS 'Stores all JAVALIB_BOOKS that available in library.';

-- COLUMN COMMENTS
COMMENT ON COLUMN EDUMAN.JAVALIB_BOOKS.ID IS 'Unique identifier of JAVALIB_BOOKS table.';
COMMENT ON COLUMN EDUMAN.JAVALIB_BOOKS.BOOK_NAME IS 'Holds the name of book.';
COMMENT ON COLUMN EDUMAN.JAVALIB_BOOKS.AUTHOR IS 'Stores the author name of book.';
COMMENT ON COLUMN EDUMAN.JAVALIB_BOOKS.CREATE_DATE IS 'Defines the date that book available in library.';

-- CREATE SEQUENCE FOR ID ATTRIBUTE
CREATE SEQUENCE EDUMAN.JAVALIB_BOOKS_IDSEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

  --
ALTER TABLE EDUMAN.JAVALIB_BOOKS ADD CONSTRAINT uc_JAVALIB_BOOKS_NAMEAUTHOR UNIQUE  (BOOK_NAME, AUTHOR);
