-- Drop package
DROP PACKAGE EDUMAN.JAVALIBRARYAPP;

-- Drop sequence/index/constraint
DROP SEQUENCE EDUMAN.JAVALIB_BOOKS_IDSEQ;
ALTER TABLE EDUMAN.JAVALIB_BOOKS DROP CONSTRAINT UC_JAVALIB_BOOKS_NAMEAUTHOR;

-- Drop tables
DROP TABLE EDUMAN.JAVALIB_BOOKS;
